# Colab 데이터 로드

In [ ]:
# Step 1.분석할 데이터가 저장된 파일을 불러와서 변수에 할당합니다.
from google.colab import files
myfile = files.upload()
import io
import pandas as pd
#pd.read_csv로 csv파일 불러오기
src_data = pd.read_csv(io.BytesIO(myfile['와인.csv']),
                       encoding='cp949')
src_data

# 로컬 데이터 로드

In [2]:
import pandas as pd
src_data = pd.read_csv('와인.csv', encoding='cp949')
src_data

알콜도수   당도  산도_ph     종류
0      9.4  1.9   3.51   레드와인
1      9.8  2.6   3.20   레드와인
2      9.8  2.3   3.26   레드와인
3      9.8  1.9   3.16   레드와인
4      9.4  1.9   3.51   레드와인
...    ...  ...    ...    ...
6492  11.2  1.6   3.27  화이트와인
6493   9.6  8.0   3.15  화이트와인
6494   9.4  1.2   2.99  화이트와인
6495  12.8  1.1   3.34  화이트와인
6496  11.8  0.8   3.26  화이트와인

[6497 rows x 4 columns]

# 공통 실습 코드

In [3]:
# Step 2.주어진 데이터를 훈련용 데이터와 검증용 데이터로 나눕니다
import numpy as np

# '알콜도수','당도','산도_ph'가지고 와인 종류 분류하기
data =  src_data[['알콜도수','당도','산도_ph']].to_numpy()
target = src_data['종류'].to_numpy()
print(data)
print(target)

# tarin test 데이터 분리
from sklearn.model_selection import train_test_split
train_data, test_data, train_target, test_target = train_test_split(
    data, target, test_size=0.2, random_state=40)

[[ 9.4   1.9   3.51]
 [ 9.8   2.6   3.2 ]
 [ 9.8   2.3   3.26]
 ...
 [ 9.4   1.2   2.99]
 [12.8   1.1   3.34]
 [11.8   0.8   3.26]]
['레드와인' '레드와인' '레드와인' ... '화이트와인' '화이트와인' '화이트와인']


In [4]:
# 의사결정트리를 통해 모델 학습
from sklearn.tree import DecisionTreeClassifier

# 모델 생성
dt = DecisionTreeClassifier(random_state=40)

# 모델 학습
dt.fit(train_data, train_target)

# 모델 score 출력
print('훈련용 정확도:',dt.score(train_data,train_target))
print('테스트용 정확도:',dt.score(test_data,test_target))

훈련용 정확도: 0.9973061381566288
테스트용 정확도: 0.8607692307692307


In [5]:
# 랜덤 포레스트를 통해 모델 학습
from sklearn.ensemble import RandomForestClassifier

# 모델 생성
dt = RandomForestClassifier(random_state=40)

# 모델 학습
dt.fit(train_data,train_target)

# 모델 score 출력
print('훈련용 데이터:',dt.score(train_data,train_target))
print('테스트용 데이터:',dt.score(test_data,test_target))

훈련용 데이터: 0.9973061381566288
테스트용 데이터: 0.89


In [6]:
# Step 3.K-Fold 교차 검증 수행(K값 자율 설정)
# 기반 모델은 의사결정트리와 랜덤 포레스트 중 더 좋은 결과를 가진 모델로 선택
from sklearn.model_selection import cross_validate, cross_val_score
from sklearn.tree import DecisionTreeClassifier
lr = DecisionTreeClassifier(random_state=40)

# cross_validate , cross_val_score 출력
score1 = cross_validate(lr, train_data, train_target, cv=5)
score2 = cross_val_score(lr, train_data, train_target, cv=5)

print('cross_validate:', score1)
print('cross_val_score:', np.mean(score2))

cross_validate: {'fit_time': array([0.01396084, 0.00897503, 0.01496077, 0.01296544, 0.00897622]), 'score_time': array([0.00199556, 0.00199461, 0.00199342, 0.00199461, 0.00199533]), 'test_score': array([0.85384615, 0.87884615, 0.84889317, 0.86814244, 0.85466795])}
cross_val_score: 0.8608791737617532
