# 문장 백터화 진행

In [1]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

sent = ("휴일 인 오늘 도 서쪽 을 중심 으로 폭염 이 이어졌는데요, 내일 은 반가운 비 소식 이 있습니다.", "폭염 을 피해서 휴일 에 놀러왔다가 갑작스런 비 로 인해 망연자실 하고 있습니 다.")
sent 

('휴일 인 오늘 도 서쪽 을 중심 으로 폭염 이 이어졌는데요, 내일 은 반가운 비 소식 이 있습니다.',
 '폭염 을 피해서 휴일 에 놀러왔다가 갑작스런 비 로 인해 망연자실 하고 있습니 다.')

In [5]:
#문장 벡터화 진행
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(sent)

idf = tfidf_vectorizer.idf_
print(dict(zip(tfidf_vectorizer.get_feature_names_out(), idf)))

{'갑작스런': 1.4054651081081644, '내일': 1.4054651081081644, '놀러왔다가': 1.4054651081081644, '망연자실': 1.4054651081081644, '반가운': 1.4054651081081644, '서쪽': 1.4054651081081644, '소식': 1.4054651081081644, '오늘': 1.4054651081081644, '으로': 1.4054651081081644, '이어졌는데요': 1.4054651081081644, '인해': 1.4054651081081644, '있습니': 1.4054651081081644, '있습니다': 1.4054651081081644, '중심': 1.4054651081081644, '폭염': 1.0, '피해서': 1.4054651081081644, '하고': 1.4054651081081644, '휴일': 1.0}


# 유사도의 예
 1. 자카드 유사도
 2. 코사인 유사도
 3. 유클리디안 유사도
 4. 멘하탄 유사도

In [6]:
# 1. 자카드 유사도
from sklearn.metrics import jaccard_score

# 두 집단의 합집합 / 두 집단의 교집합
jaccard_score(np.array([1,1,0,0]), np.array([1,1,0,1]), average=None)

# 0에 대한 유사도 : 0.5
# 1에 대한 유사도 : 0.666

array([0.5       , 0.66666667])

In [8]:
# 2. 코사인 유사도
from sklearn.metrics.pairwise import cosine_similarity

# 코사인 유사도 벡터의 내적(1에 가까울 수록 유사함)
cosine_similarity(tfidf_matrix[0:1], tfidf_matrix[1:2])

array([[0.11304078]])

In [10]:
# 3. 유클리디안 유사도(피타고라스 정리)
from sklearn.metrics.pairwise import euclidean_distances

print(euclidean_distances(tfidf_matrix[0:1], tfidf_matrix[1:2]))

# 유클리디안 유사도는 값이 1이상이 될 수 있음 정규화 필요

# 정규화
import numpy as np
def normalize(v):
    norm = np.sum(v)
    return v / norm

tfidf_norm = normalize(tfidf_matrix)
print(euclidean_distances(tfidf_norm[0:1], tfidf_norm[1:2]))

[[1.33188529]]
[[0.21243357]]


In [11]:
# 4. 맨하탄 유사도
from sklearn.metrics.pairwise import manhattan_distances

manhattan_distances(tfidf_norm[0:1], tfidf_norm[1:2])

array([[0.85654185]])