In [ ]:
#Step 1.분석할 데이터가 저장된 파일을 불러와서 변수에 할당합니다.
from google.colab import files
myfile = files.upload()
import io
import pandas as pd
#pd.read_csv로 csv파일 불러오기
fish3 = pd.read_csv(io.BytesIO(myfile['fish3.csv']),
                       encoding='cp949')
fish3

In [1]:
import pandas as pd
fish3 = pd.read_csv('fish3.csv',encoding='cp949')
fish3

종류     무게    길이       높이      두께
0    도미  242.0  25.4  11.5200  4.0200
1    도미  290.0  26.3  12.4800  4.3056
2    도미  340.0  26.5  12.3778  4.6961
3    도미  363.0  29.0  12.7300  4.4555
4    도미  430.0  29.0  12.4440  5.1340
..   ..    ...   ...      ...     ...
143  빙어   12.2  12.2   2.0904  1.3936
144  빙어   13.4  12.4   2.4300  1.2690
145  빙어   12.2  13.0   2.2770  1.2558
146  빙어   19.7  14.3   2.8728  2.0672
147  빙어   19.9  15.0   2.9322  1.8792

[148 rows x 5 columns]

In [6]:
#Step 2: 훈련용 데이터셋과 테스트용 데이터셋 나누어서 분석
from sklearn.model_selection import train_test_split

# 무게, 길이, 높이, 두께에 따른 종류 분류
data = fish3[['무게','길이','높이','두께']].to_numpy()
target = fish3['종류'].to_numpy()

# train, test 데이터 분리
훈련용_data, 테스트용_data, 훈련용_target, 테스트용_target = train_test_split(
    data, target, test_size=0.2, random_state=40)

In [7]:
#Step 3. 데이터 표준화를 진행합니다
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(훈련용_data)

표준화_훈련용_data = ss.transform(훈련용_data)
표준화_테스트용_data = ss.transform(테스트용_data)

In [9]:
# 모델을 생성하고 테스트하고 성능을 확인합니다.
from sklearn.linear_model import LogisticRegression
import numpy as np

# 로지스틱 회귀 모델 생성(C, max_iter 속성 정하기)
lr = LogisticRegression(C=10, max_iter=200)

# 모델 학습
lr.fit(표준화_훈련용_data, 훈련용_target)

# 모델 예측 결과 출력
print(lr.predict(표준화_테스트용_data))

# 분류 확률 출력
print(np.round(lr.predict_proba(표준화_테스트용_data), 3))

# 점수 출력
print(lr.score(표준화_테스트용_data, 테스트용_target))

['잉어' '농어' '농어' '농어' '농어' '빙어' '농어' '빙어' '잉어' '도미' '빙어' '강꼬치고기' '농어' '농어'
 '잉어' '농어' '농어' '강꼬치고기' '강꼬치고기' '도미' '농어' '도미' '강꼬치고기' '농어' '도미' '잉어' '농어'
 '도미' '도미' '강꼬치고기']
[[0.002 0.426 0.001 0.111 0.019 0.441]
 [0.008 0.585 0.002 0.019 0.025 0.36 ]
 [0.006 0.477 0.004 0.01  0.035 0.469]
 [0.011 0.714 0.002 0.002 0.027 0.245]
 [0.027 0.89  0.007 0.    0.074 0.003]
 [0.001 0.18  0.    0.656 0.005 0.158]
 [0.014 0.695 0.004 0.001 0.04  0.246]
 [0.    0.006 0.    0.992 0.    0.003]
 [0.01  0.302 0.035 0.    0.095 0.559]
 [0.    0.    0.989 0.    0.007 0.004]
 [0.    0.018 0.    0.97  0.    0.012]
 [0.986 0.013 0.    0.    0.    0.   ]
 [0.001 0.901 0.006 0.    0.091 0.001]
 [0.01  0.666 0.003 0.002 0.034 0.286]
 [0.008 0.414 0.014 0.001 0.066 0.497]
 [0.006 0.511 0.034 0.    0.134 0.315]
 [0.038 0.863 0.003 0.    0.039 0.058]
 [0.957 0.042 0.    0.    0.    0.   ]
 [0.631 0.365 0.    0.    0.002 0.002]
 [0.    0.    0.986 0.    0.012 0.002]
 [0.001 0.975 0.    0.    0.023 0.001]
 [0.    0.  