# BERT

In [1]:
from transformers import TFBertForMaskedLM, AutoTokenizer

In [2]:
# MODEL_NAME = 'bert-large-uncased'
MODEL_NAME = 'bert-base-uncased'
model = TFBertForMaskedLM.from_pretrained(MODEL_NAME)
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

All PyTorch model weights were used when initializing TFBertForMaskedLM.

All the weights of TFBertForMaskedLM were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForMaskedLM for predictions without further training.
c:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\tokenization_utils_base.py:1614: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprecated in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [3]:
# 스페셜 토큰 값 확인
print('start:',tokenizer.cls_token_id)
print('end:',tokenizer.sep_token_id)
print('mask',tokenizer.mask_token_id)

start: 101
end: 102
mask 103


In [4]:
# BERT는 [MASK]라는 빈칸을 예측하는데 특화되어 있습니다.
text = 'Soccer is a really fun [MASK].'
inputs = tokenizer(text, return_tensors='tf')

inputs

{'input_ids': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[ 101, 4715, 2003, 1037, 2428, 4569,  103, 1012,  102]])>, 'token_type_ids': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0, 0, 0, 0]])>, 'attention_mask': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1]])>}

In [5]:
print(inputs['input_ids'])

tf.Tensor([[ 101 4715 2003 1037 2428 4569  103 1012  102]], shape=(1, 9), dtype=int32)


In [6]:
from transformers import FillMaskPipeline
pip = FillMaskPipeline(model=model, tokenizer=tokenizer)

In [9]:
pip(text)[0]['sequence']

'soccer is a really fun sport.'

In [13]:
pip('The Avengers is a [MASK].')

[{'score': 0.0927266851067543,
  'token': 2136,
  'token_str': 'team',
  'sequence': 'the avengers is a team.'},
 {'score': 0.06522084027528763,
  'token': 12354,
  'token_str': 'parody',
  'sequence': 'the avengers is a parody.'},
 {'score': 0.0515424907207489,
  'token': 8297,
  'token_str': 'sequel',
  'sequence': 'the avengers is a sequel.'},
 {'score': 0.050337132066488266,
  'token': 16251,
  'token_str': 'superhero',
  'sequence': 'the avengers is a superhero.'},
 {'score': 0.04882737994194031,
  'token': 6329,
  'token_str': 'franchise',
  'sequence': 'the avengers is a franchise.'}]

In [18]:
for i in range(5):
    print(pip('i went to [MASK] this morning')[i]['sequence'])

i went to bed this morning
i went to work this morning
i went to sleep this morning
i went to school this morning
i went to class this morning
