In [3]:
#Step 1.분석할 데이터가 저장된 파일을 불러와서 변수에 할당합니다.
from google.colab import files
myfile = files.upload()
import io
import pandas as pd
#pd.read_csv로 csv파일 불러오기
fish3 = pd.read_csv(io.BytesIO(myfile['fish3.csv']),
                       encoding='cp949')
fish3

ModuleNotFoundError: No module named 'google'

In [17]:
import pandas as pd
fish3 = pd.read_csv('fish3.csv',encoding='cp949')
fish3

종류     무게    길이       높이      두께
0    도미  242.0  25.4  11.5200  4.0200
1    도미  290.0  26.3  12.4800  4.3056
2    도미  340.0  26.5  12.3778  4.6961
3    도미  363.0  29.0  12.7300  4.4555
4    도미  430.0  29.0  12.4440  5.1340
..   ..    ...   ...      ...     ...
143  빙어   12.2  12.2   2.0904  1.3936
144  빙어   13.4  12.4   2.4300  1.2690
145  빙어   12.2  13.0   2.2770  1.2558
146  빙어   19.7  14.3   2.8728  2.0672
147  빙어   19.9  15.0   2.9322  1.8792

[148 rows x 5 columns]

In [9]:
#Step 2: 훈련용 데이터셋과 테스트용 데이터셋 나누어서 분석

from sklearn.model_selection import train_test_split
data = fish3[ ['무게','길이','높이','두께'] ]
target = fish3['종류']

훈련용_data , 테스트용_data , 훈련용_target , 테스트용_target = train_test_split(
    data , target , test_size=0.2, random_state=40)

In [10]:
#Step 3. 데이터 표준화를 진행합니다
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(훈련용_data)
표준화_훈련용_data = ss.transform(훈련용_data)
표준화_테스트용_data = ss.transform(테스트용_data)

In [15]:
# 모델을 생성하고 테스트하고 성능을 확인합니다.
from sklearn.linear_model import LogisticRegression
import numpy as np
softmax_reg = LogisticRegression(C=50,max_iter=200)
softmax_reg.fit(표준화_훈련용_data, 훈련용_target)

print(softmax_reg.predict(표준화_테스트용_data))

print(np.round(softmax_reg.predict_proba(표준화_테스트용_data),3))

print(softmax_reg.score(표준화_훈련용_data , 훈련용_target))
print(softmax_reg.score(표준화_테스트용_data , 테스트용_target))

['농어' '농어' '잉어' '농어' '농어' '빙어' '농어' '빙어' '잉어' '도미' '빙어' '강꼬치고기' '농어' '농어'
 '잉어' '잉어' '농어' '강꼬치고기' '강꼬치고기' '도미' '농어' '도미' '강꼬치고기' '농어' '도미' '잉어' '농어'
 '도미' '도미' '강꼬치고기']
[[0.    0.48  0.    0.04  0.016 0.465]
 [0.003 0.725 0.    0.003 0.013 0.257]
 [0.001 0.462 0.    0.001 0.027 0.508]
 [0.004 0.859 0.    0.    0.009 0.129]
 [0.005 0.974 0.    0.    0.02  0.   ]
 [0.    0.17  0.    0.755 0.002 0.072]
 [0.005 0.824 0.    0.    0.019 0.152]
 [0.    0.001 0.    0.999 0.    0.   ]
 [0.002 0.122 0.014 0.    0.115 0.749]
 [0.    0.    0.998 0.    0.002 0.   ]
 [0.    0.004 0.    0.995 0.    0.001]
 [0.999 0.001 0.    0.    0.    0.   ]
 [0.    0.928 0.001 0.    0.071 0.   ]
 [0.003 0.786 0.    0.    0.016 0.194]
 [0.002 0.281 0.004 0.    0.073 0.641]
 [0.001 0.292 0.015 0.    0.19  0.502]
 [0.016 0.966 0.    0.    0.007 0.011]
 [0.982 0.018 0.    0.    0.    0.   ]
 [0.785 0.215 0.    0.    0.    0.   ]
 [0.    0.    0.994 0.    0.005 0.   ]
 [0.    0.997 0.    0.    0.003 0.   ]
 [0.    0.  

In [16]:
reg = LogisticRegression(C=50, max_iter=200)

reg.fit(훈련용_data, 훈련용_target)

print(reg.predict(테스트용_data))
print(np.round(reg.predict_proba(테스트용_data),3))
print(reg.score(훈련용_data , 훈련용_target))
print(reg.score(테스트용_data , 테스트용_target))

['잉어' '농어' '잉어' '농어' '농어' '농어' '농어' '빙어' '잉어' '도미' '빙어' '강꼬치고기' '농어' '농어'
 '잉어' '잉어' '농어' '강꼬치고기' '강꼬치고기' '도미' '농어' '도미' '강꼬치고기' '농어' '도미' '빙어' '연어'
 '도미' '도미' '강꼬치고기']
[[0.    0.419 0.    0.    0.044 0.536]
 [0.002 0.797 0.    0.    0.012 0.189]
 [0.    0.454 0.    0.    0.035 0.511]
 [0.001 0.925 0.    0.    0.004 0.069]
 [0.    0.997 0.    0.    0.002 0.   ]
 [0.011 0.671 0.    0.    0.027 0.291]
 [0.001 0.901 0.    0.    0.009 0.089]
 [0.    0.    0.    1.    0.    0.   ]
 [0.    0.088 0.    0.    0.097 0.815]
 [0.    0.    1.    0.    0.    0.   ]
 [0.    0.    0.    1.    0.    0.   ]
 [1.    0.    0.    0.    0.    0.   ]
 [0.    0.864 0.    0.    0.135 0.   ]
 [0.001 0.857 0.    0.    0.011 0.132]
 [0.    0.24  0.    0.    0.077 0.684]
 [0.    0.205 0.    0.    0.192 0.603]
 [0.001 0.996 0.    0.    0.001 0.002]
 [1.    0.    0.    0.    0.    0.   ]
 [0.993 0.007 0.    0.    0.    0.   ]
 [0.    0.    1.    0.    0.    0.   ]
 [0.    0.998 0.    0.    0.002 0.   ]
 [0.    0.  

c:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
